import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../portfolio-app-second/components/navigation/Navbar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased `}>
        <div
          className={
            "w-screen h-screen bg-gradient-to-b from-blue-100 to-red-100 flex flex-col"
          }
        >
          <div className={`h-24`}>
            <Navbar />
          </div>

          <div className={"h-[calc(100vh_-_6rem)]"}>{children}</div>
        </div>
      </body>
    </html>
  );
}
